export const GET_TRANSACTIONS = 'transactions/GET_TRANSACTIONS';
export const GET_TRANSACTIONS_COMPLETED = 'transactions/GET_TRANSACTIONS_COMPLETED';
export const GET_TRANSACTIONS_FAILED = 'transactions/GET_TRANSACTIONS_FAILED';
export const GET_TRANSACTION = 'transactions/GET_TRANSACTION';
export const GET_TRANSACTION_COMPLETED = 'transactions/GET_TRANSACTION_COMPLETED';
export const GET_TRANSACTION_FAILED = 'transactions/GET_TRANSACTION_FAILED';
